### ISSUE TITLE
The godot 4 branch is working?

### ISSUE THREAD

**Issue by CHIESOFTWARE** [Zylann/godot_voxel#303] opened 2021-08-05 14:36 UTC
I want to test the SDFGI in Godot 4 using this plugin to see how the performance change compare to 3.3 but i see that godot 4 branch is not been updated since 16 month ago.

**Comment by Zylann** [comment] 2021-08-05 19:29
That branch was an old early compilation test, I should actually delete it I think.
Porting to Godot 4 is planned once the engine gets more stable.

Duplicate of https://github.com/Zylann/godot_voxel/issues/127

**Closed by Zylann** 2021-08-05 19:29 UTC
