### ISSUE TITLE
`do_sphere` with `MODE_TEXTURE_PAINT` breaks modifiers in chunk

### ISSUE THREAD

**Issue by matthewhilton** [Zylann/godot_voxel#529] opened 2023-06-29 13:04 UTC
I'm using the voxel tool with `MODE_TEXTURE_PAINT` to paint textures on terrain:
```
_vt.set_mode(VoxelTool.MODE_TEXTURE_PAINT)
_vt.set_texture_index(1)
_vt.set_texture_opacity(1.0)
_vt.do_sphere(t.origin, 0.5)
```

However, it seems the paint spheres are conflicting with Voxel mesh modifiers.

It seems regardless of the radius of the sphere, it causes all the modifiers in that "chunk" to be ignored.

For example here, without any painting, it looks like this, modifiers are placed underneath the path to add terrain:

![image](https://github.com/Zylann/godot_voxel/assets/17095477/48d67dce-6003-4523-a5ea-58ce9423375c)

But when a number of spheres are painted along the path, the modifiers in each "chunk" seem to disappear:

(note the spheres being painted are tiny, nowhere near the size of the cutouts they are making)

![image](https://github.com/Zylann/godot_voxel/assets/17095477/20abfd54-2701-4289-9229-9b840605234b)

**Comment by Zylann** [comment] 2023-06-29 18:17
Do you have a minimal test project? I did a quick test but could not reproduce it.

**Comment by matthewhilton** [comment] 2023-06-30 12:09
See this example project: [VoxelModifierTest.zip](https://github.com/Zylann/godot_voxel/files/11916073/VoxelModifierTest.zip)

You can see by commenting/uncommenting the `do_sphere` in the script the Mesh modifier will appear/disappear.

I've also stumbled onto something else here that may or may not be related: The `VoxelModifierMesh` sdf seems to be 'unbaking' itself?

For e.g. when running the project above I had to add `%VoxelModifierMesh.mesh_sdf.bake()` otherwise the mesh modifier would not show at all. And when I save and reload the project, the modifier in the editor loses its baked sdf. When running the game in the editor i also get an error:

```
E 0:00:00:0618   zylann::voxel::VoxelMeshSDF::_b_set_data: Condition "Vector3iUtil::is_empty_size(res)" is true.
  <C++ Source>   modules\voxel\edition\voxel_mesh_sdf_gd.cpp:440 @ zylann::voxel::VoxelMeshSDF::_b_set_data()
```

What is weird is that `VoxelModifierSphere` seems to be unaffected by any of this.

**Comment by Zylann** [comment] 2023-06-30 19:53
> You can see by commenting/uncommenting the do_sphere in the script the Mesh modifier will appear/disappear.

Are you also doing this in `_ready` in your project? That's incredibly early, I think if you have saved data to load it won't work properly, because it still takes some time to load the edits, even in full load. However the module is lacking a check for that currently, so `is_area_editable` returns `true` even though edits haven't loaded yet. Though I think in your test project that wouldn't be the issue.

> I've also stumbled onto something else here that may or may not be related: The VoxelModifierMesh sdf seems to be 'unbaking' itself?

There is a bug in the code that loads `VoxelMeshSDF` from `.tres`, therefore it fails to load. Should be fixed in 25137035b4a629299ca9a10c6efc8aef6a53a3cd.

> What is weird is that VoxelModifierSphere seems to be unaffected by any of this

Sphere doesn't need to load data the way mesh does. But when it comes to chunks disappearing when using texture paint, not sure why.

I launched your project after fixing the baking issue, and this is the result:
![image](https://github.com/Zylann/godot_voxel/assets/1311555/e2b98803-9d69-4698-b6a6-daa0dc557ca8)
```gdscript
extends VoxelLodTerrain

func _ready():
	#%VoxelModifierMesh.mesh_sdf.bake()
	
	var _vt = get_voxel_tool()
	_vt.set_mode(VoxelTool.MODE_TEXTURE_PAINT)
	_vt.set_texture_index(1)
	_vt.set_texture_opacity(1.0)
	_vt.do_sphere(%VoxelModifierMesh.global_position, 1)
```

It doesn't seem to reproduce anymore.

**Comment by Zylann** [comment] 2023-07-05 20:54
Since e752f3efef3630cdc44223d38d8e071c585fe18f the module now prevents early edits until all data is loaded also when `full_load_mode` is enabled.

**Comment by Zylann** [comment] 2023-07-23 18:01
Is this still a problem?

**Comment by Zylann** [comment] 2023-09-02 17:35
Closing for now, if the problem still happens it could be reopened.

**Closed by Zylann** 2023-09-02 17:35 UTC
Labels: bug, Needs more info
