### ISSUE TITLE
Godot 4.0 compatibility

### ISSUE THREAD

**Issue by luiscla27** [Zylann/godot_voxel#222] opened 2020-12-29 20:23 UTC
Hello, is **godot_voxel** compatible with Godot 4.0??

The reason I ask is because [documentation says](https://github.com/Zylann/godot_voxel/blob/master/doc/02_build-voxel-tools.md) to use the `master` branch (4.0). However, I remember reading in one of your YouTube videos that some of your plugins doesn't use Godot 4.0 features, I'm not sure what that means.

Can you please clarify the current work for version 4.0?

**Comment by Zylann** [comment] 2020-12-29 22:19
None of my work uses Godot 4.0 yet. I'm slowly working on a documentation update.
For now you should use the Godot 3.2 branch.

**Comment by luiscla27** [comment] 2020-12-29 23:24
Thank you, I'll do that :)

**Comment by Zylann** [comment] 2021-01-31 15:17
Closing as duplicate of #127

**Closed by Zylann** 2021-01-31 15:17 UTC
Labels: Documentation
