### ISSUE TITLE
Implement Transvoxel for smooth voxels

### ISSUE THREAD

**Issue by zauberparacelsus** [Zylann/godot_voxel#2] opened 2016-09-16 00:15 UTC
Might I suggest implementing a smooth voxel system?  Transvoxel would be a good one to implement, as it supports Level of Detail with seamless transitions.

http://transvoxel.org/

**Comment by Zylann** [comment] 2016-09-16 00:17
Interesting, I didn't know this one. How is it different from marching cubes?

**Comment by zauberparacelsus** [comment] 2016-09-16 00:20
It's an extended version of Marching Cubes, designed to create LOD transitions so that more distant areas use less geometry (and therefor require less resources to render).

Another option is Naive Surface Nets.  If you have code for generating blocky voxel meshes, you're already halfway done.  Naive Surface Nets can also be extended to have variable levels of smoothing, so that they can be used to represent both blocky and smooth geometry.

https://0fps.net/2012/07/12/smooth-voxel-terrain-part-2/

**Comment by Zylann** [comment] 2016-09-16 00:41
Well, I thought about LOD before, and it extends beyond rendering. The data has to have LODs too, mostly because it can take a lot of memory. Maybe it's doable with some kind of octree? Also, there could be multiple cameras looking at the same dataset from different points of views. But for now I don't feel I'll implement that. And if there is only one viewer it's possible to optimize the LOD a little bit, I guess.

My current renderer is not only designed to render cubes, but any mesh indexed by type (but I lack a demo of it). If a smooth renderer has to be implemented, then it's a different interpretation of the data, and it will be a separate one, working on a separate channel. For example, using channel 1 for smooth terrain, and channel 2 for blocky buildings.

Last note: I'm not currently active on this module, because I work on other projects and I have less time now. I'll probably come back to work again in this field but can't say when.

**Comment by Zylann** [comment] 2016-09-16 00:54
The idea I had was to add an option in the module to set the number of LOD levels. It would currently be 1 level. Level 2 would subdivide the current grid into a 1-level octree structure, and so on, so the root is still a grid and extends to the farthest the viewer can see.

But I said earlier only one viewer would be supported yet. So instead of having a deep octree, why not having indexed grids? No need for hashing, and accessing a LOD is just a matter of an index (I wonder if I am clear enough?).

When dealing with voxel data, I also found OpenVDB, which subdivides blocks by a factor of 8 instead of 2 (by block I mean "cubic chunks", if we were to use Minecraft's terminology). However I feel it's too abrupt of a transition, or maybe I miss something.

**Comment by Zylann** [comment] 2017-01-14 20:31
Just an update to say that I'm currently working on a Transvoxel implementation for this module. The state of Godot 3.0 is very unstable so I can't test or show much, but it's something I would like to experiment with.

**Comment by Corruptinator** [comment] 2017-01-15 23:46
Nice! I can imagine that this type of special voxelization can be used for multiple purposes: endless high-def Voxel terrain or useful tool asset to create stages/levels and saving them to a file.

**Comment by Corruptinator** [comment] 2017-01-15 23:46
Can't wait for 3.0, its the era of modern 3D Dev Design!  : )

**Comment by Zylann** [comment] 2017-04-06 21:51
I just pushed an update... the module is now able to polygonize smooth voxels.
It's a rough starting point, so they aren't textured or colored for now. I'm not decided yet on the API, sorry if it looks messy. I also updated the example project :)

**Comment by Corruptinator** [comment] 2017-04-07 07:06
Zylann, I might be able to help you out with the untextured Smooth Voxels, a while ago I asked on the Godot QA about applying a seamless texture wrap to a 3d Object and the answer was very valuable:

[https://godotengine.org/qa/12952/automatic-seamless-texture-object-through-materialshader](url)

Or if you want the code that works, here you go (Answer was provided by _Mollusca_ BTW):


**VERTEX SHADER:**

VAR1 = vec4(SRC_NORMAL.x, SRC_NORMAL.y, SRC_NORMAL.z, 0.0);
VAR2 = vec4(SRC_VERTEX.x, SRC_VERTEX.y, SRC_VERTEX.z, 0.0);


**FRAGMENT SHADER:**

uniform texture diffuse;
uniform float sharpness;
uniform float texture_scale;

vec2 uv_x = vec2(VAR2.z, 1.0 - VAR2.y) / texture_scale;
vec2 uv_y = vec2(VAR2.z, 1.0 - VAR2.x) / texture_scale;
vec2 uv_z = vec2(VAR2.x, 1.0 - VAR2.y) / texture_scale;

vec3 col_x = tex(diffuse, uv_x).xyz;
vec3 col_y = tex(diffuse, uv_y).xyz;
vec3 col_z = tex(diffuse, uv_z).xyz;

vec3 weights = abs(VAR1.xyz) - vec3(0.2); // the 0.2 adds additional sharpness, not necessarily needed
weights.x = pow(weights.x, sharpness);
weights.y = pow(weights.y, sharpness);
weights.z = pow(weights.z, sharpness);
weights = max(weights, vec3(0.0));
weights /= dot(weights, vec3(1.0));

DIFFUSE = (weights.x * col_x + weights.y * col_y + weights.z * col_z);


Also, if you really want to go crazy and apply blending a texture to a different one based on height, terrain, or biome purposes, then check out "Godot Tutorial #6 Splatmaps":
[https://www.youtube.com/watch?v=RLAG4RbT-5U](url)

**Comment by Zylann** [comment] 2017-04-07 08:30
Is this triplanar mapping?
Also shaders aren't working yet in 3.0, so I'll have to wait a little before trying.

**Comment by Corruptinator** [comment] 2017-04-07 09:06
It is Tri-Planar Mapping and I just wanted to point out a possible resource/idea should you have the chance to try it out, just simple heads up for good cause.

**Comment by Zylann** [comment] 2017-04-07 12:41
The video link is broken :(

**Comment by zauberparacelsus** [comment] 2017-04-11 16:42
@Zylann Is your smooth voxels implementation Transvoxel as you had planned, or did you go with another algorithm?

**Comment by Zylann** [comment] 2017-04-11 17:42
It is Transvoxel. It's not complete yet, for now it only does the modified marching cubes because I'm working on the design of the LOD system before going further.

**Comment by Corruptinator** [comment] 2017-04-11 18:42
Progress is progress.  :)

**Comment by zauberparacelsus** [comment] 2017-05-05 01:21
I found two implementations of the Cubical Marching Squares algorithm, another voxel mesher algorithm.  It is additionally able to generate "adaptive geometry", meaning it can generate simplified geometry for areas that need it less.

https://github.com/mkeeter/kokopelli/blob/master/libfab/asdf/cms.c
https://bitbucket.org/GRassovsky/cubical-marching-squares

original paper: http://www.csie.ntu.edu.tw/~cyy/publications/papers/Ho2005CMS.pdf

**Comment by Zylann** [comment] 2017-05-05 09:17
I'm also interested in implementing dual contouring, so at this point I think this module could integrate different choices of algorithms, if it doesn't involve too much differences in ways of storing data^^ (I like to keep logic and data separated)

**Comment by Zylann** [comment] 2019-12-25 03:49
I'm working again on Transvoxel in the `transvoxel` branch, and I'm getting closer to a true implementation which includes transition cells. There are several things to note about it:

### It is faster

The current smooth terrain uses basic marching cubes with marching squares skirts for hiding LOD cracks. Here are the timings when the two algorithms build a 32x32x32 mesh:

- DMC takes 33ms
- Transvoxel takes 7ms

Reasons for such a speed up are mostly caused by the inclusion of vertex sharing as part of the main iteration, while DMC was using a generic map to find vertices at the same positions.

### A shader will be needed to render blocks

This means the node will no longer allow to assign a vanilla material, it will have to be a `ShaderMaterial`. This is because Transvoxel requires the vertex shader to dynamically displace some of the vertices to make room for transition meshes at runtime, for any combination of the 6 sides being bordered by blocks of lower LOD or not. In theory it could be re-meshed as a single mesh everytime, but remeshing takes time and it would slow it down.

### Differences from the paper

So far I followed the paper, also taking help from an existing implementation found here: https://github.com/BinaryConstruct/Transvoxel-XNA/blob/master/Transvoxel/SurfaceExtractor/ported/TransvoxelExtractor.cs, but I started to consider tweaking it since I'm now getting a better grasp on it.

Most notably, this:
![image](https://user-images.githubusercontent.com/1311555/71431215-47509700-26c8-11ea-98e4-c9c7957dd123.png)

Instead of placing transition meshes inside low-resolution blocks connecting to high-resolution voxels, I decided to do the opposite: placing them in high-resolution meshes, connecting to low-resolution. At the moment, I think it would be better because it allows to use the same voxel buffer, skipping half voxels for the low-resolution side. Thoughts?

### Negative-axis side vertices never get re-used along valid axes

Even though Transvoxel comes with vertex sharing built-in, I discovered none of the vertices lying on the negative sides of a block would never be connected together. I could not find a fix for this yet, not sure if I did something wrong.

This can be observed by randomly shaking vertices based on their index in a vertex shader:
![image](https://user-images.githubusercontent.com/1311555/71431390-774c6a00-26c9-11ea-9b73-fd71edd5bb99.png)

To be continued.
Note: at time of writing, the `transvoxel` branch on Github does not include all my local work yet.

**Comment by Zylann** [comment] 2019-12-26 20:03
Small update:
Mostly been fixing bugs since last post, and came up with a better test scene to test LOD stitching.

### Transition meshes mostly working in one direction

https://www.youtube.com/watch?v=scNtmx2HiS0&feature=youtu.be

I still have to implement a small correction to transition vertices, they need to be adjusted according to the surface normal as described in the paper.
Once I have a decent implementation, I will look into transforming it so it can support all 6 sides of the block, as it's currently implemented only for the -Z side.

### Moving vertices causes sharp artifacts

The idea to fit transition meshes is to "push" normal vertices from the side of the block to insert them. So far I've done it by detecting which vertices lie on the side, and offset those towards the inside of the block.
However, if a vertex is not exactly on the side, but close enough to remain in the transition area, it will not be moved, producing a sharp artifact, like seen here:

![image](https://user-images.githubusercontent.com/1311555/71488811-7d059500-281a-11ea-8686-bcd2fa314e1d.png)

They won't be seen from the player's point of view (since it will be on the other side), but it's worth mentionning as I'm not sure yet if it's good enough to ignore them.

**Comment by Zylann** [comment] 2020-01-01 01:38
Transvoxel is now implemented in the master branch.

### Speed

If you try smooth terrain, it should be a bit faster. However, now there are a bit more meshes to render, and the engine has to compute transition masks to determine which seams to activate. This incurs a performance hit in neighbor-checking that I'd like to optimize later on.

### Seams

As described in previous posts, this implementation relies on a vertex shader to reposition vertices around seams to make transitions smoother. However, such shaders are not actually required for the terrain to render. If you don't use one, you'll get the same result as the old mesher, where seams would be perpendicular across blocks of different LOD.
If you want the vertex shader trick, your shader should include the following:
```glsl
// Bitmask telling which of the 6 faces of the block are bordered by a block of lower resolution
uniform int u_transition_mask;

vec3 get_transvoxel_position(vec3 vertex_pos, vec4 vertex_col) {

	int border_mask = int(vertex_col.a);
	int cell_border_mask = border_mask & 63; // Which sides the cell is touching
	int vertex_border_mask = (border_mask >> 6) & 63; // Which sides the vertex is touching

	// If the vertex is near a side where there is a low-resolution neighbor,
	// move it to secondary position
	int m = u_transition_mask & (cell_border_mask & 63);
	float t = float(m != 0);

	// If the vertex lies on one or more sides, and at least one side has no low-resolution neighbor,
	// don't move the vertex.
	t *= float((vertex_border_mask & ~u_transition_mask) == 0);

	// Position to use when border mask matches
	vec3 secondary_position = vertex_col.rgb;
	return mix(vertex_pos, secondary_position, t);
}

void vertex() {
	VERTEX = get_transvoxel_position(VERTEX, COLOR);
}
```

### Future

This can be improved in the upcoming versions. Notably, Transvoxel mentions a binary-search technique which could help fixing distant landscape, which will be worked on in https://github.com/Zylann/godot_voxel/issues/60#

There are also texturing techniques which would allow to use more complex shading and custom-painted surfaces, by introducing material ID and weights to voxel data (no mentions of transparency tho).

**Comment by tinmanjuggernaut** [comment] 2020-01-04 07:44
I know you worked hard on this. Good job so far. I had a chance to test it out and here's what I found using VT 716b8205, and Godot 389b7939bf.

In summary, it's 40-50% slower, produces better meshes for odd areas, and fixes the holes. The NORMAL shader fix is still required for heightmap. The provided vertex shader didn't work at all for me.

### Definite Improvements

* I no longer see holes in the mesh as shown in #63 .

* Odd areas are meshed better.

![image](https://user-images.githubusercontent.com/632766/71761536-5e805780-2f06-11ea-87ad-96a3c87ebf0f.png)


### Performance stats

Using my demo. FPS is from sitting in the initial starting point and looking around. Other figures with ranges are from moving around. Build out times are approximate, but definitely different.

```
Scene: heightmap_smooth_lod
			DMC				Transvoxel
Build out:		1-1.5s				3s
FPS:			275-348				200-218
Memory static:	 	117-123				147
Memory dynamic: 	51-55				45

Objects: 		14,220				29,575
Objects drawn: 		234-330				420
Vertices Drawn:		2,330,820-3,055,596		2,327,361
```
```
Scene: noise_smooth_lod
			DMC				Transvoxel
Build out: 		2-2.5				4-5
FPS:			275-300				140-180
Memory static: 		108-143				153-211
Memory dynamic: 	50-75				40-61

Objects: 		14,342-19,034			29,789-42,133
Objects drawn: 		368-450				499-550
Vertices Drawn: 	5,554,269-6,723,201 (@215)	3,904,659 (@130) - 4,120,764 (@145) - 4,610,043 (@95)
```


### NORMAL shader fix still needed
When I removed the fix from my shader:
* No black faces on noise terrain
* Black faces on heightmap on distant LODs, usually on what appeared to be vertical faces. Quite visible through the fog.


### Provided Vertex Shader produces artifacts
Adding the provided vertex shader code to my shader produced this. I did nothing else but add it. Here the NORMAL fix has been turned off.

![image](https://user-images.githubusercontent.com/632766/71761448-8cb16780-2f05-11ea-8ec3-bcc2b497b3f1.png)

**Comment by Zylann** [comment] 2020-01-04 16:59
> In summary, it's 40-50% slower

Slower to *render* I assume, because the meshing process is definitely faster. I guess this is the result of Godot culling being terrible, because transition meshes increases mesh instance count, you can tell by the number of objects drawn.
As for noise-based terrains, they are now slower to generate but that's entirely on the generator being unoptimized.

About the spiky artifacts: this one nagged me for a while, and I thought I fixed it for the main parts of the meshes, but for transition meshes I haven't tested the shader extensively enough, some booboo remains to be fixed.

> I also noticed at a view distance of 4096 and LOD count of 8, the farthest LODS don't connect

This is very odd. There are several possibilities, either it's the generator reaching an edge case, or a bug in the mesher but I'd find this less likely.

**Comment by tinmanjuggernaut** [comment] 2020-01-04 18:06
> I noticed a thin crack in the middle of a mesh once

Regarding the square cracks with the vertex shader, those appeared all over the landscape. Some were much bigger. Some appeared/disappeared based upon camera angle, but not position.

> Slower to render I assume, because the meshing process is definitely faster. I guess this is the result of Godot culling being terrible, because transition meshes increases mesh instance count, you can tell by the number of objects drawn.

Hmm, the number of objects is twice as many. But the number drawn is not much more. And the number of vertices is significantly less in some cases. With all of that, the FPS is halved. 

I would have expected the number of vertices to be the performance factor, or at least the number of drawn objects. Not the number of objects overall. If the meshing is nearly 500% faster then the number of total objects must be a ridiculous bottleneck in the renderer, and the number of vertices hardly a factor.

**Comment by Zylann** [comment] 2020-01-04 18:49
> Some appeared/disappeared based upon camera angle, but not position.

Woah?

> Hmm, the number of objects is twice as many. But the number drawn is not much more. And the number of vertices is significantly less in some cases. With all of that, the FPS is halved.

That's because Godot has to *cull* twice as many :p and culling is really not the biggest strength of Godot right now

> If the meshing is nearly 500% faster then the number of total objects must be a ridiculous bottleneck in the renderer

It is. Been mentionned in https://github.com/godotengine/godot/issues/23998

**Comment by Zylann** [comment] 2020-01-04 23:32
I fixed transition meshes in 8056f7e6798a85a4f33ebae577266416ec41cbdb, now they scale with LOD properly.
I tested a proper shader with `VoxelLodTerrain`, the difference is subtle. I really need to improve `VoxelStreamImage` some day.

**Comment by Zylann** [comment] 2020-01-05 05:00
Fixed thin cracks in 462e453cf45c11373cfd1f60d7218df4dccd8f78

**Comment by tinmanjuggernaut** [comment] 2020-01-06 19:25
As of 3ead96, I can now include your shader code into my shader without artifacts, but I don't see any difference in game. Taking a shot in photoshop, I do see a difference, but without the shader looks better to me. In some places they're the same, but in others, without the shader blends in more.

![image](https://user-images.githubusercontent.com/632766/71842568-e62fb700-30fc-11ea-928d-f60c8738c382.png)

**Comment by Zylann** [comment] 2020-01-06 20:21
It depends on the situations maybe. I noticed the shading of transition meshes is sometimes a bit weird, becoming black for no reason.
But there is still a main remaining reason for them to not be 100% seamless: deep-sampling using binary search is not implemented yet, so isolevel between blocks can still vary a lot (https://github.com/Zylann/godot_voxel/issues/60).

**Comment by Zylann** [comment] 2020-01-07 02:14
About FPS performance: I just pushed a branch called `visibility_as_being_in_world`. In this branch, instead of using the `visible` property to show and hide block LODs, I directly remove them from the world, or add them back. In debug mode I went from 150 fps to 180.

**Comment by tinmanjuggernaut** [comment] 2020-01-08 18:47
All my scenes and materials look good except one.  This shader shows seams:

![image](https://user-images.githubusercontent.com/632766/72002731-efe32700-3282-11ea-9204-1ee56a3ad671.png)

It uses vertex displacement, which pushes the vertices along their normals a minor amount to give texture to the ground. If vertex displacement is removed, the ground is sealed up again.

If I try to use the seam shader fix above, it produces all sorts of craziness because my shader also uses `world_vertex_coords`. The craziness changes depending on camera angle, so it's a matrix transform issue. But I played around with all the transform matrices trying to convert VERTEX, and COLOR going into the function, or on the return value, but wasn't able to get it to convert properly.

**Comment by Zylann** [comment] 2020-01-08 18:52
Problem with your shader, can't really say much since the reference implementation works. Maybe it's caused by the inputs your displacement is based on, they have to match between blocks.

**Comment by tinmanjuggernaut** [comment] 2020-01-08 22:00
> About FPS performance: I just pushed a branch called `visibility_as_being_in_world`.

Much faster. It's a little jerky or halting when building out, and occasionally when moving fast over the terrain as paged areas are building.

Updated performance stats:

```
Scene: heightmap_smooth_lod
			DMC		Transvoxel	T2
Build out:		1-1.5s		3s		3s
FPS:			275-348		200-218		250-270
Memory static:	 	117-123		147	136
Memory dynamic: 	51-55		45		45

Objects: 		14,220		29,575		29,575
Objects drawn: 		234-330		420		444
Vertices Drawn:		2,330,820	2,327,361	2,497,701
```
```
Scene: noise_smooth_lod
			DMC		Transvoxel	T2
Build out: 		2-2.5		4-5		5s
FPS:			275-300		140-180		190-220
Memory static: 		108-143		153-211		141-207
Memory dynamic: 	50-75		40-61		41-85

Objects: 		14,342-19,034	29,789-42,133	29,789-41,728
Objects drawn: 		368-450		499-550		465-772
Vertices Drawn 1: 	5,554,269	3,904,659 @130	3,503,532 @228
Vertices Drawn 2:	6,723,201 @215	4,120,764 @145	4,216,845 @175
Vertices Drawn 3:			4,610,043 @95	8,786,157 @125
```

**Comment by Zylann** [comment] 2020-01-09 00:08
Do you think I should merge that approach? Eventually it may be tested again once the 4.0 renderer arrives.

**Comment by tinmanjuggernaut** [comment] 2020-01-09 07:03
Yes, transvoxel is such a big performance hit (even up to 70% on my space scene) and this approach gets some of that back. I tested it extensively today and had no issues. At worst it's no slower.

I'd expect that you'd revisit a lot of things once 4 becomes available, such as vsync being required.

**Comment by tinmanjuggernaut** [comment] 2020-01-09 21:12
My space scene is pretty heavy duty with a noise height of 1500 and shaders for sky and ground. With DMC I could get 120-150fps in complex areas. With transvoxel I might get around 1/3rd of that. The new approach had a big impact on other scenes, but doesn't do much for this one.

I ran it under the msvc profiler and found:
* my CPU isn't maxed
* the noise source is a huge sap 

![image](https://user-images.githubusercontent.com/632766/72103571-69067b00-3364-11ea-9d80-fd3485cb7926.png)

Still a year to go for the SimplexNoise patent. I wonder about the OpenSimplexNoise optimizations and that guy's new noise algorithm, [SuperSimplexNoise](https://github.com/KdotJPG/New-Simplex-Style-Gradient-Noise). Maybe all of these variations could be put into Godot.

Next, I switched my project to multithreaded and all of a sudden my game went up to a respectable 65-80fps in heavy areas. Navigation throughout the scene was noticeably smoother. However, voxel updates were then ridiculously slow as per #48. Basically you sit there in the same spot for a good 5-10 seconds before updates happen.

**Comment by Zylann** [comment] 2020-01-09 21:53
I was considering giving a try at `FastNoise` tbh. Or even its SIMD version.

**Comment by tinmanjuggernaut** [comment] 2020-01-09 22:07
Apparently SuperSimplexNoise and FastSimplexStyleNoise are both faster than FastNoise Simplex according to benchmarks in the readme I linked, and unencumbered. But FastNoiseSIMD seems fastest (and more complex).

**Comment by tinmanjuggernaut** [comment] 2020-01-09 22:57
I was able to create a new VoxelStream with FastNoise. It's still slow, but I'll experiment and see if I can get an optimal stream.

Here's 3D Voronoi under TransVoxel:

![image](https://user-images.githubusercontent.com/632766/72111630-539a4c80-3376-11ea-9556-3f9a5953fc00.png)

**Comment by Zylann** [comment] 2020-01-11 21:49
Since Transvoxel is mostly implemented now, I'll close this issue. Some specific areas remain to be done, such as texturing and binary-search sampling, but those have their own issues.

**Closed by Zylann** 2020-01-11 21:49 UTC
Labels: Partially implemented, enhancement
