### ISSUE TITLE
Plan to separate terrain systems between blocky and smooth?

### ISSUE THREAD

**Issue by menip** [Zylann/godot_voxel#175] opened 2020-08-06 03:40 UTC
Is there a plan to separate the blocky/smooth terrain systems? I'm personally all for it, as I think it would make code easier to understand, and also I plan to only work with blocky terrain for my project :slightly_smiling_face: 

https://github.com/Zylann/godot_voxel/blob/aa2300866d6147e3f9e85cc8820f063877e6c686/terrain/voxel_terrain.cpp#L911

**Comment by Zylann** [comment] 2020-08-06 12:51
Duplicate of https://github.com/Zylann/godot_voxel/issues/41

I'm still not decided, but unless we want to have the benefits of being able to run both *at the same time* with a single `VoxelTerrain`, it might make things a bit more simpler.
i.e if we separate them and a game wants to use both in its world, then the module will have to do twice the work inside `_process` to manage blocks.
This is one of the things I keep for the next large refactoring.

**Closed** 2020-08-06 13:18 UTC
