### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by JekSun97** [Zylann/godot_voxel#617] opened 2024-04-03 12:38 UTC
**Is your feature request related to a problem? Please describe.**
I want to make a water landscape, with caves, etc., with pre-prepared locations, like in the game Subnautica, but it’s not possible to do this in the editor?

**Describe the solution you'd like**
Develop a simple plugin for editing voxels in the editor and saving the resource for loading it in the game

**Describe alternatives you've considered**
Write a plugin on Godot itself using GDScript?

**Comment by Zylann** [comment] 2024-04-03 17:34
Duplicate of https://github.com/Zylann/godot_voxel/issues/527

**Closed by Zylann** 2024-04-03 17:34 UTC

**Comment by JekSun97** [comment] 2024-04-04 08:46
@Zylann Got it, how can you make such smooth holes in voxels like in the game Subnautica?
