### ISSUE TITLE
No voxels showing on linux

### ISSUE THREAD

**Issue by creikey** [Zylann/godot_voxel#110] opened 2020-01-20 01:08 UTC
After building  off of the latest godot master with the module in the `modules/` folder, I was able to successfully open [the demo](https://github.com/Zylann/voxelgame) , however there are no voxels visible, and the main screen looks as following:
![image](https://user-images.githubusercontent.com/28424206/72691990-44d23900-3ade-11ea-970f-53711412e748.png)

There are no errors in console or editor.

**Comment by creikey** [comment] 2020-01-20 01:17
Does not work on GLES2 either

**Comment by tinmanjuggernaut** [comment] 2020-01-20 04:54
Did you change your channel to sdf?

**Comment by blockspacer** [comment] 2020-01-20 05:42
@creikey
Can you see voxels in https://github.com/tinmanjuggernaut/voxelgame ?

**Comment by creikey** [comment] 2020-01-20 06:22
@blockspacer No, I cannot.

@tinmanjuggernaut Sorry, I'm unsure of what you mean by channel in this context, could you clarify?

**Comment by tinmanjuggernaut** [comment] 2020-01-20 07:33
See #4 https://github.com/tinmanjuggernaut/godot_voxel/blob/master/doc/03_create-terrain.md
Open up your stream settings and try changing the channel.

Also there are several demos in Zylann's and in mine, both linked above. You can't see voxels in any of them? It's been working for a while cross platform, so it's more likely you have a wrong setting (Zylann's demo may have it wrong by default as some things recently changed in the noise generator).

If none of these work you need to post more details and do more thorough testing. One sentence doesn't give us any information with which to help you.

**Comment by blockspacer** [comment] 2020-01-20 14:17
@creikey 

Can you provide more details about your hardware (CPU, GPU), please.

Can you provide commit hashes of https://github.com/godotengine/godot and https://github.com/tinmanjuggernaut/voxelgame ?

Can you run other 3d projects with godot ?

BTW: godot_voxel HTML5 builds are not supported, produces similar result

**Comment by tinmanjuggernaut** [comment] 2020-01-20 18:04
I just built Godot and VT master for linux. All my demos (in /fps_demo/) work. Your screenshot is from one of Zylann's demos. Most of which work, but some don't. You can also try my binaries: http://tokisan.com/godot-binaries

**Comment by Zylann** [comment] 2020-01-21 14:04
I made a few breaking changes recently, some symbols got renamed. My demo is fairly outdated at this point.
Check if you get any errors in the log.

**Comment by tobischw** [comment] 2020-03-19 23:34
I am running into the same issue on Windows. I am following [this](https://github.com/Zylann/godot_voxel/blob/master/doc/03_create-terrain.md) tutorial. 

Tried different channel settings, increased the `Far` in the Camera, and followed pretty much just the tutorial. I am using the pre-built binaries, if that helps (the latest from whatever website they are hosted on).

I do see this in the output:
```
Constructing VoxelDataLoader
Constructing VoxelMeshUpdater
```

but that's about it - no progress or anything else. I am new to Godot, so let me know if I can send a log or something. The demo scenes all gave me a bunch of missing resources error messages, so maybe I should try and get that running somehow.

**Comment by Zylann** [comment] 2020-03-20 00:30
Here is a working minimal project:
[Minimal.zip](https://github.com/Zylann/godot_voxel/files/4357427/Minimal.zip)
When played, it should show a simple blocky landscape. Can you see it?

**Comment by tinmanjuggernaut** [comment] 2020-03-20 04:30
The binaries are old, so you need my demo scenes from the exact link specified on my binaries page. That will give you the old version of the demos. 

Zylann's minimum project may not work because things have been renamed since November. 

However creating a new project as shown in the video should work fine.

Are you creating a VoxelTerrain or VoxelLodTerrain? For VT, you need to create a library as shown in the video, but it's no longer in the text tutorial. For both, you need to specify the right channel that matches the data source. E.G.VT, channel TYPE, heightmap should all work. Did you watch the video posted? 

The channel selection and settings are more automated in newer versions if you build from source, or use my new binaries that will come in about a week.

**Comment by tobischw** [comment] 2020-03-20 17:27
Sorry, I was just going off the text tutorial because I tend to dislike video tutorials. I will check it out, thank you very much!

**Comment by dark-penguin** [comment] 2020-06-12 22:26
I can confirm this; the "Zylann/voxelgame" demo does not show the terrain. But this only happens with the "default" demo, which is the "smooth terrain"; the "blocky terrain" demo works fine. The stats in the corner do update, but no matter where I look, I don't see "Looking at..." line pop up (I don't even know if it's supposed to pop up in the "smooth terrain" demo).

I'm on Debian Buster amd64 with RX550, and I'm using Godot 3.2-stable built with this module on January 30th, so it's not exactly "current master". However, I'm not interested in LOD terrain at all - I just saw an issue and thought more data might be of some use to someone. (What I am interested in is GDNative and Godot 4 support :-P )

**Comment by Zylann** [comment] 2020-06-12 22:30
> built with this module on January 30th, so it's not exactly "current master".

I strongly suggest testing with master.

**Comment by dark-penguin** [comment] 2020-06-13 00:07
I was trying to slack off from rebuilding Godot to test this, but I actually even have a build container ready. :)

With Godot 3.2 from git, this module from master right now, and Zylann/voxelgame from master right now, both "blocky" and "smooth" demos work!

Since I had the exact same problem and now it's fixed, and the OP seems to have disappeared, we can probably close this?

**Comment by creikey** [comment] 2020-06-13 01:26
When I originally opened this issue I thought that the build might have just been broken so didn't so any more digging, then a day later forgot about the module. There could have been a myriad of things wrong with my setup, so if it works for others this issue can be safely closed.

**Comment by Zylann** [comment] 2020-06-13 01:31
Thanks for the update.

**Closed by Zylann** 2020-06-13 01:31 UTC
Labels: Needs more info
