### ISSUE TITLE
Keep getting this error code.

### ISSUE THREAD

**Issue by probedrone** [Zylann/godot_voxel#365] opened 2022-03-25 20:53 UTC
I keep getting this error in the voxel game project as well as my own game project. I have no idea what to do about it.
![image](https://user-images.githubusercontent.com/20933246/160199331-0f64557c-0be7-4ea4-bf5c-691e3ef59aa9.png)

**Comment by Zylann** [comment] 2022-03-25 20:59
Duplicate of https://github.com/Zylann/godot_voxel/issues/360

**Comment by probedrone** [comment] 2022-03-25 21:31
Both the 3.x and 4.0 branches give the issue, using the versions built using Github action. My OS is Windows 10.

**Comment by Zylann** [comment] 2022-03-25 21:36
If you got it with Godot 4.0, what was the logged message there? The screenshot you posted seems to be from Godot 3.

**Comment by probedrone** [comment] 2022-03-26 01:01
Trying with the issue you used it works on my side with the Godot4 branch now. It must of just been because I was using an older version of the 4 branch without the fixes is my guess?

**Comment by Zylann** [comment] 2022-03-26 01:17
So far it's hard to say what the origin of the issue even is, so can't really say wether or not anything got fixed^^"

**Comment by probedrone** [comment] 2022-03-26 02:01
The issue tho seems to persist in the 3.X branch of godot however.

**Comment by Zylann** [comment] 2022-03-26 02:58
3.x is using pretty much the same code so I have no idea why that would happen there, apart from that `sizeof(int)` you could change to a `sizeof(uint32_t)` https://github.com/Zylann/godot_voxel/blob/726bd807506cef7f7e8ee34ba774ec793ec5f034/streams/region/region_file.cpp#L367
And if that doesnt fix anything, if you look at the full snippet for `godot3.x`, I dont see anything else wrong with the code, apart from Godot potentially having a bug of some sort https://github.com/Zylann/godot_voxel/issues/360#issuecomment-1079436156

**Comment by probedrone** [comment] 2022-03-26 04:50
An additional note to this, I can confirm that both the Mono and Windows build give the error

**Comment by Zylann** [comment] 2022-03-26 17:32
I just tried the same process with the `godot3.x` branch and the `master` branch of the voxel demo from Github, launched it, no issue occurred.

**Comment by probedrone** [comment] 2022-03-30 06:44
Tried testing the latest build and still received the error. I noticed it happens when I walk a certain amount away from spawn in it.
Here is the full debugger log.
![image](https://user-images.githubusercontent.com/20933246/160768160-59ff9bcf-1d6c-4005-90db-da49d1518236.png)

**Comment by Zylann** [comment] 2022-03-30 20:46
Do you keep testing this with the same project without redownloading a clean copy?

I inverted the logged info, but if corrected it basically shows the following:
- The amount of data to write is `1508` bytes
- Before writing data, `f->get_position()` returned `16404`.
- After writing the data, `f->get_position()` returned `17934`.
- The difference between the two position tells it moved by `1530` bytes... which is 22 bytes more, despite the code looking correct (excluding the inverted logging) https://github.com/Zylann/godot_voxel/blob/2659cfba96555a6db5deeb74f5709156899133c6/streams/region/region_file.cpp#L360-L373

**Comment by probedrone** [comment] 2022-03-31 09:16
I tested with a clean copy and everything. I have an idea that it may have to do with how it is trying to save the data and it is getting corrupted somehow?

**Comment by Zylann** [comment] 2022-03-31 18:13
The question is, how can it possibly get corrupted, and why so subtly? Like, it's not *very* wrong or even crashy, it's always just slightly off, and only when some people test it, so far only in Godot 3.

**Comment by probedrone** [comment] 2022-03-31 18:19
This is all rather baffling indeed. :\
I was hoping to use the voxel plugin for my own VR RPG game

**Comment by Zylann** [comment] 2022-03-31 18:40
You don't have to use `VoxelStreamRegionFiles` tho, `VoxelStreamSQLite` works too

**Comment by probedrone** [comment] 2022-04-02 06:51
Weird, in VoxelStreamRegionFiles, if I keep the path field blank I get no issues with it?

**Comment by Zylann** [comment] 2022-04-02 16:11
Do you keep getting the same error message? My last commits added more checks around `store_buffer`.
Also does your terrain have the setting `run_stream_in_editor` enabled?

**Comment by probedrone** [comment] 2022-04-02 19:36
I have run_stream_in_editor disabled.
Here is the issue it is coming with now when the path field is filled. 
![image](https://user-images.githubusercontent.com/20933246/161398498-73a67d3c-e535-41b8-aa8a-b2ebc7044936.png)

**Comment by Zylann** [comment] 2022-04-02 19:40
Yeah at this point there is nothing else I can do... `store_buffer` is pretty much not working as expected.

**Comment by probedrone** [comment] 2022-04-02 20:27
Getting this error in the StoreBuffer project.
![image](https://user-images.githubusercontent.com/20933246/161400055-8759a067-3c39-41da-800f-02a77fe8d689.png)

**Comment by Zylann** [comment] 2022-04-02 20:31
That's the call stack, not the error. But you shouldn't get any error. When I test with [this build](https://github.com/Zylann/godot_voxel/actions/runs/2067558844), I don't get any.
Are you able to get the same error with an official Godot version?

**Comment by probedrone** [comment] 2022-04-02 20:37
After extensive testing, I do not get any errors with the StoreBuffer test in other projects.

**Comment by Zylann** [comment] 2022-04-02 20:40
What do you mean "in other projects"? StoreBuffer is a project. You mean with other Godot versions?

**Comment by probedrone** [comment] 2022-04-02 20:44
Yeah I meant other Godot versions. I also noticed that now the issue only comes up in the Mono build of Godot after the fixes?

**Comment by Zylann** [comment] 2022-04-02 20:46
After which fixes?

**Comment by probedrone** [comment] 2022-04-02 20:53
After switching to the uint64_t fix the regular Godot Voxel build works but not the latest Mono Godot Voxel build. 
I been using Mono this whole time since I need C# for the more intense number crunching for AI and RPG stats in my own game.

**Comment by Zylann** [comment] 2022-04-02 21:03
I have no idea why Mono makes a difference here... it was already a nightmare to make the CI produce working Mono builds^^" Maybe try compiling Godot yourself, in case it makes a difference somehow...

**Comment by probedrone** [comment] 2022-04-07 21:53
Any luck on finding a way to fix this issue? I am honestly stumped over it.

**Comment by Zylann** [comment] 2022-04-07 22:01
Nothing new, sorry.
Have you tried building a Mono version yourself?

**Comment by Zylann** [comment] 2022-04-11 00:51
I'll close this issue because it was a duplicate. I'll link it in https://github.com/Zylann/godot_voxel/issues/360#issuecomment-1094430575 because it contains some insight.

**Closed by Zylann** 2022-04-11 00:51 UTC
Labels: bug, help wanted
