### ISSUE TITLE
Can we adjust the size of the Voxel grid?

### ISSUE THREAD

**Issue by Skotchy** [Zylann/godot_voxel#232] opened 2021-02-13 17:24 UTC
I would like to increase the size of the grid to 10 units instead of 1.

I'm building an RTS game and I need to use integers only for movement.  An increased grid size allows me to do this.

otherwise my characters move around 1 block per tick, 10 blocks per second.

Thanks for any response!

**Comment by Zylann** [comment] 2021-02-13 23:33
You can scale the terrain.
You can also scale your own nodes. Godot won't care much since transforms are floats anyways.

**Comment by Skotchy** [comment] 2021-02-14 06:39
Are you talking about in the module itself? thanks for your fast reply.

**Comment by Zylann** [comment] 2021-02-14 15:21
Yeah, if you want bigger voxels, you can use the scale property of the terrain. It's a spatial node, every spatial has a scale.

**Comment by Skotchy** [comment] 2021-02-14 15:35
i tried this and bunch of other things, but it doesn't to work? I appreciate your responses thanks.

**Comment by Zylann** [comment] 2021-02-14 16:19
What doesnt work?

When I try it, scaling works:

https://user-images.githubusercontent.com/1311555/107882308-70da0c80-6ee0-11eb-8a33-44465f438a5c.mp4

**Comment by Skotchy** [comment] 2021-02-14 16:23
I am using the Region Files stream,  so i don't have the in editor view. I'm using only script.

**Comment by Zylann** [comment] 2021-02-14 16:24
Then assign scale in script.

`get_node("VoxelTerrain").scale = Vector3(10, 10, 10)`

**Comment by Skotchy** [comment] 2021-02-14 16:26
> 
> 
> Then assign scale in script.
> 
> `get_node("VoxelTerrain").scale = Vector3(10, 10, 10)`
> 
> But you could better do it in the editor if the node is in the scene originally.

this does not work, i think maybe its because of the region file streaming

**Comment by Zylann** [comment] 2021-02-14 16:27
The stream should have no relation to the scaling of the terrain.

Things are working when I try locally so if you can reproduce the issue even with latest build, you could provide a test project so I can see if you have a particular configuration that makes it break.

**Comment by Zylann** [comment] 2021-02-14 16:29
Keep in mind that the scaling feature has been added to latest: https://voxel-tools.readthedocs.io/en/latest/changelog/#ongoing-development-master
And is not supported in the `godot3.2.3` branch.

**Comment by Skotchy** [comment] 2021-02-14 16:31
> 
> 
> Keep in mind that the scaling feature has been added to latest: https://voxel-tools.readthedocs.io/en/latest/changelog/#ongoing-development-master
> And is not supported in the `godot3.2.3` branch.

ah makes sense! i plan of updating when godot 4.0 comes out. thanks for your help!

**Comment by Zylann** [comment] 2021-02-14 16:32
Latest is still based on Godot 3.2.4 ;)

**Comment by Zylann** [comment] 2024-05-06 19:33
Closing in favor of #105

**Closed by Zylann** 2024-05-06 19:33 UTC
Labels: question
