### ISSUE TITLE
Scenes converted to MultiMeshItems using the "scene" property aren't colliding.

### ISSUE THREAD

**Issue by syncreticgames** [Zylann/godot_voxel#485] opened 2023-02-16 03:23 UTC
I'm seeing a VoxelInstanceLibraryMultiMeshItem fail to collide when created from the "scene" property in editor, even though the CollisionShape3D shows up in the "Collision Shapes" array. When I create this as a VoxelInstanceLibrarySceneItem it collides as expected. No issues with simply using it as a scene, but thought I would take advantage of the MultiMesh efficiency if it works. Is MultiMesh conversion applying colliders correctly in the current state?

**Comment by MGilleronFJ** [comment] 2023-02-16 10:25
Can you provide a minimal reproduction project?

**Comment by syncreticgames** [comment] 2023-02-17 00:47
Interesting, I'm sure I must have done something wrong in the scene setup...it's called "biginteractable.tscn", thanks so much for your willingness to investigate together!

[VoxelTestMinimal.zip](https://github.com/Zylann/godot_voxel/files/10762156/VoxelTestMinimal.zip)

**Comment by Zylann** [comment] 2023-02-17 18:57
![image](https://user-images.githubusercontent.com/1311555/219760470-da6b5425-ea0a-40f3-a5ce-c85ac3fccd8e.png)
Hmmmm no issue in your scene, but somehow colliders are offset

**Comment by Zylann** [comment] 2023-02-17 19:25
I think the issue is caused by an incorrect calculation of transforms in the instancer. It uses global block positions, which is fine for multimeshes because those are used with RenderingServer directly. But colliders use nodes, which means their transform must be relative to the instancer node, not global.
Turns out your terrain is offset by -3.71369 in the Y coordinate, which uncovers the bug.

**Comment by Zylann** [comment] 2023-02-17 19:57
Should be fixed in 0c56dd885f6aca713b47f9bcfcf41248cd7ee1ea

**Comment by syncreticgames** [comment] 2023-02-18 02:58
Amazing, thank you so much!!

**Closed** 2023-02-18 02:58 UTC
Labels: bug
